---
all:
  hosts:
    AD_server:
    Clearpass_Server:
    central:
      ansible_host: apigw-prod2.central.arubanetworks.com
      ansible_connection: httpapi
      ansible_network_os: aruba_central
      ansible_httpapi_use_ssl: True
      ansible_httpapi_central_access_token: PFgi2OSTxk8jZgnjsty25g3pZXQNoV35
  children:
    south_wing:
      hosts:
        access_1_sw:
          ansible_host: 10.251.8.103
          ansible_user: admin
          ansible_password: aruba123
          ansible_network_os: arubanetworks.aoscx.aoscx
          ansible_connection: arubanetworks.aoscx.aoscx
          ansible_aoscx_validate_certs: False
          ansible_aoscx_use_proxy: False
          device_id: 3
          ansible_httpapi_use_ssl: True
#--- pre 6.3 step 12
#          ansible_host: 10.251.8.103
#          ansible_user: admin
#          ansible_password: aruba123
#--- pre 6.3 step 8
#          ansible_connection: network_cli
#          ansible_network_os: arubanetworks.aoscx.aoscx
#          ansible_httpapi_use_ssl: True
#          ansible_acx_no_proxy: True
#          ansible_httpapi_validate_certs: False
        core_1_sw:
          device_id: 1
    west_wing:
      children:
        ubuntu_servers:
          hosts:
            ubuntu_awx:
              ansible_host: 10.251.8.201
              ansible_user: student
              ansible_password: aruba
        ww_devices:
          hosts:
            Aruba_gateway:
            core_2_ww:
                ansible_host: 10.251.8.102
                ansible_user: admin
#-- pre 6.6 step 2                
                ansible_password: aruba123
                ansible_connection: network_cli
#                ansible_password: !vault |
#                  $ANSIBLE_VAULT;1.1;AES256
#                  62386464323363633830623466656166313034393161363035643565303136386232376663346462
#                  3833653663643036326330313638363836643166636132350a373265303066613639306234313536
#                  37353530656236656131316263363563653665646633333332643263623035623332333634376536
#                  6166313233623062350a356239393664313065303731313232653238336566386532306261346637
#                  6263

                #ansible_connection: httpapi
                ansible_network_os: arubanetworks.aoscx.aoscx
                ansible_httpapi_use_ssl: True
                ansible_acx_no_proxy: True
                ansible_httpapi_validate_certs: False
                device_id: 2
