#- hosts: access_1_sw
- hosts: core_2_ww
  gather_facts: no
  roles:
    - role: arubanetworks.aoscx_role
  #collections:
  #  - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /home/student/ansible_venv/bin/python3
    ansible_connection: network_cli
  tasks:
    - include_role:
        name: show_info
      when: device_id == 2
